## 1. NumPy 소개 및 기본 개념

### 왜 NumPy를 사용해야 할까요?

NumPy는 파이썬에서 대규모 수치 및 행렬 연산을 빠르고 효율적으로 처리하기 위한 핵심 라이브러리입니다. 그 이유는 다음과 같습니다.

- **`ndarray`**: 파이썬 리스트보다 메모리를 효율적으로 사용하고 연산 속도가 매우 빠른 다차원 배열 객체(`ndarray`)를 제공합니다.
- **벡터화(Vectorization)**: 반복문 없이 배열 전체에 대한 연산을 수행하여 코드를 간결하게 만들고 실행 속도를 높입니다.
- **브로드캐스팅(Broadcasting)**: 서로 다른 크기의 배열 간에도 산술 연산이 가능하도록 자동으로 배열을 확장해 줍니다.
- **생태계의 기반**: Pandas, SciPy, Scikit-learn, PyTorch 등 데이터 과학 및 머신러닝 분야의 주요 라이브러리들이 NumPy를 기반으로 만들어졌습니다.

In [ ]:
# NumPy 라이브러리를 np라는 별칭으로 불러옵니다.
import numpy as np

# 0부터 11까지의 정수로 배열을 생성하고, 3행 4열의 형태로 재구조화합니다.
x = np.arange(12).reshape(3, 4)

# 배열의 형태(shape), 차원(ndim), 데이터 타입(dtype)을 출력합니다.
print("Shape:", x.shape)  # (3, 4) -> 3행 4열
print("Dimensions:", x.ndim) # 2 -> 2차원 배열
print("Data Type:", x.dtype) # int64 (시스템에 따라 int32일 수 있음)

Shape: (3, 4)
Dimensions: 2
Data Type: int64


### 파이썬 리스트 vs NumPy 배열

NumPy 배열의 가장 큰 특징은 **모든 원소가 동일한 데이터 타입**이어야 한다는 것입니다. 이 덕분에 메모리에 연속적으로 데이터를 저장할 수 있어 연산 효율이 극대화됩니다. 또한, 리스트와 달리 배열 전체에 대한 산술 연산(벡터화 연산)이 매우 간단합니다.

In [ ]:
# 파이썬 리스트: 원소별 산술 연산이 직접적으로는 불가능합니다.
lst = [1, 2, 3]
# lst + 1  # 이 코드는 TypeError를 발생시킵니다.

# NumPy 배열: 배열의 모든 원소에 대해 한 번에 연산을 적용할 수 있습니다.
arr = np.array([1, 2, 3])

# 배열의 모든 원소에 1을 더합니다.
print("arr + 1:", arr + 1)

# 배열의 모든 원소에 3을 곱합니다.
print("arr * 3:", arr * 3)

# 2차원 배열 간의 연산 예시
A = np.arange(6).reshape(2, 3)  # 0~5까지의 숫자로 2x3 배열 생성
B = np.ones((2, 3))            # 모든 원소가 1인 2x3 배열 생성

# 같은 크기의 배열끼리 덧셈 연산을 수행합니다.
print("\nMatrix A:\n", A)
print("Matrix B:\n", B)
print("A + B:\n", A + B)

arr + 1: [2 3 4]
arr * 3: [3 6 9]

Matrix A:
 [[0 1 2]
 [3 4 5]]
Matrix B:
 [[1. 1. 1.]
 [1. 1. 1.]]
A + B:
 [[1. 2. 3.]
 [4. 5. 6.]]


### `ndarray`의 핵심 속성

- **`shape`**: 각 차원의 크기를 알려주는 튜플. (예: `(3, 4)`는 3행 4열)
- **`ndim`**: 차원의 수. (예: 1차원, 2차원)
- **`size`**: 배열에 있는 전체 원소의 개수. `shape` 튜플의 모든 값을 곱한 것과 같습니다.
- **`dtype`**: 원소의 데이터 타입. (예: `int64`, `float32`)
- **`itemsize`**: 원소 하나가 차지하는 메모리 크기 (바이트 단위).
- **`strides`**: 다음 차원의 원소로 이동하기 위해 건너뛰어야 할 메모리 바이트 크기를 나타내는 튜플. 메모리 구조를 이해하는 데 도움이 됩니다.

In [ ]:
x = np.arange(12).reshape(3, 4)

print("shape:", x.shape, "ndim:", x.ndim, "size:", x.size)
print("dtype:", x.dtype, "itemsize:", x.itemsize)
print("strides:", x.strides) # (32, 8) -> 다음 행으로 가려면 32바이트, 다음 열로 가려면 8바이트 이동 (int64 기준)

shape: (3, 4) ndim: 2 size: 12
dtype: int64 itemsize: 8
strides: (32, 8)


### dtype 심화 및 형 변환

데이터의 종류(정수, 실수, 불리언 등)와 정밀도에 따라 적절한 `dtype`을 선택하는 것이 중요합니다. `astype()` 메서드를 사용하면 배열의 데이터 타입을 변경할 수 있으며, 이 과정에서 새로운 배열이 생성(복사)됩니다.

In [ ]:
# float64 타입의 배열 생성
x = np.array([1.2, 3.4, 5.6], dtype=np.float64)
print("Original array (float64):", x, x.dtype)

# int32 타입으로 변환 (소수점 이하 버림)
int_x = x.astype(np.int32)
print("Casted to int32:", int_x, int_x.dtype)

# float32 타입으로 변환 (정밀도 변경)
float32_x = x.astype(np.float32)
print("Casted to float32:", float32_x, float32_x.dtype)

# np.can_cast()로 안전하게 형 변환이 가능한지 확인할 수 있습니다.
# 'safe' 캐스팅은 데이터 손실이 없을 때만 True를 반환합니다.
print("\nCan safely cast int32 to int16?", np.can_cast(np.int32, np.int16, casting='safe')) # 큰 타입을 작은 타입으로 바꾸면 데이터 손실 위험이 있어 False
print("Can safely cast int16 to int32?", np.can_cast(np.int16, np.int32, casting='safe')) # 작은 타입을 큰 타입으로 바꾸는 것은 안전하므로 True

Original array (float64): [1.2 3.4 5.6] float64
Casted to int32: [1 3 5] int32
Casted to float32: [1.2 3.4 5.6] float32

Can safely cast int32 to int16? False
Can safely cast int16 to int32? True


## 2. 배열 생성하기

### `arange` & `linspace`

- **`np.arange(start, stop, step)`**: `range` 함수와 유사하지만, 정수뿐만 아니라 실수 간격으로도 배열을 생성할 수 있습니다. 부동소수점 오차에 주의해야 합니다.
- **`np.linspace(start, stop, num)`**: 시작점과 끝점 사이를 지정된 개수(`num`)만큼 균일하게 나눈 값들로 배열을 생성합니다. 구간을 정확하게 나눌 때 유용합니다.

In [ ]:
# 0부터 1 미만까지 0.2 간격으로 배열 생성
a = np.arange(0, 1, 0.2)
print("arange(0, 1, 0.2):", a)

# 0부터 1까지 5개의 균일한 간격으로 배열 생성
b = np.linspace(0, 1, 5)
print("linspace(0, 1, 5):", b)

# reshape와 함께 사용하기: -1부터 1까지 9개의 점으로 3x3 격자 생성
grid = np.linspace(-1, 1, 9).reshape(3, 3)
print("\nGrid created with linspace and reshape:\n", grid)

arange(0, 1, 0.2): [0.  0.2 0.4 0.6 0.8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

Grid created with linspace and reshape:
 [[-1.   -0.75 -0.5 ]
 [-0.25  0.    0.25]
 [ 0.5   0.75  1.  ]]


### `zeros`, `ones`, `full`, `eye`, `diag`

특정한 패턴을 가진 배열을 빠르게 생성할 수 있습니다.

- **`np.zeros(shape)`**: 모든 원소가 0인 배열 생성
- **`np.ones(shape)`**: 모든 원소가 1인 배열 생성
- **`np.full(shape, value)`**: 모든 원소가 지정된 `value`인 배열 생성
- **`np.eye(N)`**: 주대각선이 1이고 나머지는 0인 N x N 단위 행렬 생성
- **`np.diag(v)`**: 주어진 1차원 배열 `v`를 대각 원소로 갖는 2차원 배열 생성

In [ ]:
# 모든 원소가 0인 2x3 배열 (float32 타입)
z = np.zeros((2, 3), dtype=np.float32)
print("zeros (2,3) with float32:\n", z, z.dtype)

# 모든 원소가 1인 2x3 배열
o = np.ones((2, 3))
print("\nones (2,3):\n", o)

# 모든 원소가 7인 2x3 배열
f = np.full((2, 3), 7)
print("\nfull (2,3) with 7:\n", f)

# 3x3 단위 행렬
I = np.eye(3)
print("\neye (3):\n", I)

# 대각 원소가 [10, 20, 30]인 3x3 대각 행렬
D = np.diag([10, 20, 30])
print("\ndiag ([10, 20, 30]):\n", D)

zeros (2,3) with float32:
 [[0. 0. 0.]
 [0. 0. 0.]] float32

ones (2,3):
 [[1. 1. 1.]
 [1. 1. 1.]]

full (2,3) with 7:
 [[7 7 7]
 [7 7 7]]

eye (3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

diag ([10, 20, 30]):
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]


### 난수 생성 (Generator API)

NumPy의 새로운 난수 생성 방식은 `np.random.default_rng()`를 사용하는 것입니다. `seed` 값을 고정하면 항상 동일한 난수 시퀀스를 얻을 수 있어 실험의 **재현성**을 보장합니다.

- **`rng.random(size)`**: [0.0, 1.0) 범위에서 균등 분포의 난수 생성
- **`rng.integers(low, high, size)`**: [`low`, `high`) 범위에서 정수 난수 생성
- **`rng.normal(loc, scale, size)`**: 평균(`loc`), 표준편차(`scale`)를 따르는 정규 분포 난수 생성

In [ ]:
# 시드를 42로 고정하여 재현 가능한 난수 생성기(rng)를 만듭니다.
rng = np.random.default_rng(42)

# [0, 1) 범위의 균등 분포에서 2x3 크기의 난수 배열 생성
U = rng.random((2, 3))
print("Uniform randoms (2,3):\n", U)

# [0, 10) 범위에서 정수 5개 생성
K = rng.integers(0, 10, size=5)
print("\nRandom integers [0, 10):", K)

# 평균 0, 표준편차 1인 표준 정규 분포에서 2x2 크기의 난수 배열 생성
N = rng.normal(0, 1, (2, 2))
print("\nNormal randoms (2,2):\n", N)

Uniform randoms (2,3):
 [[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]

Random integers [0, 10): [7 7 7 7 5]

Normal randoms (2,2):
 [[-0.85304393  0.87939797]
 [ 0.77779194  0.0660307 ]]


## 3. 배열 재구조화 및 차원 조작

### `reshape`, `ravel`, `flatten`

배열의 형태를 바꾸거나 1차원으로 펼칠 수 있습니다.

- **`reshape(shape)`**: 새로운 형태로 배열을 변환. 전체 원소 개수는 동일해야 합니다. 가능한 경우 원본 데이터를 공유하는 **뷰(view)**를 반환합니다.
- **`ravel()`**: 배열을 1차원으로 펼칩니다. 가능한 경우 **뷰(view)**를 반환합니다.
- **`flatten()`**: 배열을 1차원으로 펼칩니다. 항상 새로운 배열을 생성하는 **복사본(copy)**을 반환합니다.

In [ ]:
# 0부터 11까지의 1차원 배열 생성
x = np.arange(12)

# 3행 4열로 재구조화
A = x.reshape(3, 4)
print("Original array x:", x)
print("Reshaped array A:\n", A)
print("Shape of A:", A.shape)

# ravel()은 뷰를 반환할 수 있습니다 (이 경우 원본 x와 메모리를 공유).
# is 연산자는 두 변수가 동일한 객체를 가리키는지 확인합니다.
print("\nDoes A.ravel() share memory with x?", np.shares_memory(A.ravel(), x))

# flatten()은 항상 복사본을 반환합니다.
B = A.flatten()
print("Does B (from flatten) share memory with A?", np.shares_memory(B, A))

# .flags['OWNDATA']로 자신의 데이터를 소유하는지(복사본인지) 확인할 수 있습니다.
print("Does B own its data?", B.flags['OWNDATA'])

Original array x: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape of A: (3, 4)

Does A.ravel() share memory with x? True
Does B (from flatten) share memory with A? False
Does B own its data? True


### 차원 조작: `transpose`, `moveaxis`, `expand_dims`, `squeeze`

배열의 축 순서를 바꾸거나, 불필요한 차원을 추가/제거할 수 있습니다.

- **`arr.T`** 또는 **`arr.transpose()`**: 축의 순서를 뒤집습니다. (예: `(2,3,4)` -> `(4,3,2)`)
- **`np.moveaxis(arr, source, destination)`**: 특정 축(`source`)을 원하는 위치(`destination`)로 이동시킵니다.
- **`np.expand_dims(arr, axis)`**: 지정된 축(`axis`)에 크기가 1인 새로운 차원을 추가합니다.
- **`np.squeeze(arr)`**: 크기가 1인 차원을 모두 제거합니다.

In [ ]:
# (2, 3, 4) 형태의 3차원 배열 생성
X = np.arange(24).reshape(2, 3, 4)
print("Original shape (X):", X.shape)

# moveaxis: 0번 축(batch)을 맨 뒤(-1)로 이동 (예: NCHW -> CHWN)
Y = np.moveaxis(X, 0, -1)
print("Shape after moveaxis(0, -1):", Y.shape)

# expand_dims: 1차원 배열(5,)에 0번 축을 추가하여 2차원 배열(1, 5)로 만듭니다.
z_1d = np.arange(5)
Z = np.expand_dims(z_1d, axis=0)
print("\nOriginal shape (z_1d):", z_1d.shape)
print("Shape after expand_dims(axis=0):", Z.shape)

# squeeze: (3, 1, 1) 형태 배열에서 크기가 1인 축들을 제거하여 1차원 배열(3,)로 만듭니다.
w_3d = np.array([[[1]], [[2]], [[3]]])
W = np.squeeze(w_3d)
print("\nOriginal shape (w_3d):", w_3d.shape)
print("Shape after squeeze:", W.shape)

Original shape (X): (2, 3, 4)
Shape after moveaxis(0, -1): (3, 4, 2)

Original shape (z_1d): (5,)
Shape after expand_dims(axis=0): (1, 5)

Original shape (w_3d): (3, 1, 1)
Shape after squeeze: (3,)


## 4. 인덱싱과 슬라이싱

### 기본 인덱싱 및 슬라이싱

배열의 특정 원소나 부분 배열을 선택하는 방법입니다.

- **`arr[row, col]`**: 특정 위치의 원소(스칼라)를 선택합니다.
- **`arr[start:stop:step]`**: 슬라이싱을 통해 부분 배열을 선택합니다. 슬라이싱 결과는 대부분 원본 배열의 데이터를 공유하는 **뷰(view)**이므로, 뷰를 수정하면 원본도 변경됩니다.
- **`:`** : 해당 축의 모든 원소를 선택합니다.

In [ ]:
A = np.arange(12).reshape(3, 4)
print("Original Array A:\n", A)

# 1번 행, 2번 열의 원소 선택 (0-based indexing)
scalar = A[1, 2]
print("\nA[1, 2]:", scalar)

# 모든 행의 1번 열 선택 (결과는 1차원 배열)
column_1 = A[:, 1]
print("A[:, 1]:", column_1)

# 슬라이싱 예시: 0번 행부터 2번 행까지 2칸씩 건너뛰고, 열은 역순으로 선택
S = A[0:3:2, ::-1]
print("\nSliced Array S:\n", S)

# 슬라이싱 결과(뷰)를 수정하면 원본 배열도 변경됩니다.
print("\nModifying the view S...")
S[0, 0] = 999
print("Array A after modification:\n", A) # A[0, 3]의 값이 999로 바뀜

Original Array A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

A[1, 2]: 6
A[:, 1]: [1 5 9]

Sliced Array S:
 [[ 3  2  1  0]
 [11 10  9  8]]

Modifying the view S...
Array A after modification:
 [[  0   1   2 999]
 [  4   5   6   7]
 [  8   9  10  11]]


### 브로드캐스팅(Broadcasting)

NumPy의 가장 강력한 기능 중 하나로, 서로 다른 형태(shape)의 배열 간에도 산술 연산이 가능하게 해줍니다. 규칙은 다음과 같습니다.

1. 두 배열의 차원 수가 다르면, 차원 수가 적은 배열의 앞쪽(왼쪽)에 크기가 1인 차원을 추가하여 차원 수를 맞춥니다.
2. 두 배열의 각 차원을 뒤에서부터 비교하면서, 크기가 같거나 둘 중 하나의 크기가 1이면 호환 가능합니다.
3. 연산 시, 크기가 1인 차원은 다른 배열의 해당 차원 크기에 맞춰 가상으로 확장(복사)됩니다.

만약 어떤 차원이라도 이 규칙을 만족하지 못하면 `ValueError`가 발생합니다.

In [5]:
A = np.arange(12).reshape(3, 4)  # shape: (3, 4)
b = np.array([1, 2, 3, 4])        # shape: (4,)

print(A)
print("---")
print(b)
print("---")

# A(3,4)와 b(4,)의 브로드캐스팅
# 1. b의 shape이 (1, 4)로 확장됨
# 2. (1, 4)가 (3, 4)에 맞춰 3번 복제되어 연산됨
print("A (3,4) + b (4,):\n", A + b)

c = np.array([10, 20, 30])      # shape: (3,)
# print(A + c) # A(3,4)와 c(3,)는 마지막 차원이 4와 3으로 달라 오류 발생!

# c를 (3,1) 형태로 만들어 브로드캐스팅이 가능하게 합니다.
# c[:, None]은 c를 열 벡터로 만듭니다. (np.newaxis와 동일)
c_col = c[:, np.newaxis]           # shape: (3, 1)
print("\nc_col's shape:", c_col.shape)
# A(3,4)와 c_col(3,1)의 브로드캐스팅
# 1. c_col의 (3,1)이 (3,4)에 맞춰 열 방향으로 4번 복제되어 연산됨
print("A (3,4) + c_col (3,1):\n", A + c_col)

# 실전 패턴: 데이터 표준화
X = np.random.randn(5, 3) # 5x3 데이터 행렬
# 각 열(feature)의 평균을 계산. keepdims=True로 차원을 (1,3)으로 유지
mu = X.mean(axis=0, keepdims=True) # shape: (1, 3)
X_centered = X - mu # (5,3) - (1,3) -> (1,3)이 5번 복제되어 연산
print("\nShape of centered data:", X_centered.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---
[1 2 3 4]
---
A (3,4) + b (4,):
 [[ 1  3  5  7]
 [ 5  7  9 11]
 [ 9 11 13 15]]

c_col's shape: (3, 1)
A (3,4) + c_col (3,1):
 [[10 11 12 13]
 [24 25 26 27]
 [38 39 40 41]]

Shape of centered data: (5, 3)


### 축(axis) 기반 연산

`sum`, `mean`, `max` 등의 집계 함수는 `axis` 인자를 통해 연산을 적용할 축을 지정할 수 있습니다.

- **`axis=0`**: 열 방향으로 연산. 각 열의 원소들을 모아 계산합니다. (결과의 shape에서 0번 축이 사라짐)
- **`axis=1`**: 행 방향으로 연산. 각 행의 원소들을 모아 계산합니다. (결과의 shape에서 1번 축이 사라짐)
- **`keepdims=True`**: 연산 후에도 해당 축을 크기 1로 유지시켜, 브로드캐스팅에 유리하게 만듭니다.

In [7]:
A = np.arange(12).reshape(3, 4)
print("Original Array A:\n", A)

# axis=0: 각 열의 평균 (결과 shape: (4,))
col_mean = A.mean(axis=0)
print("\n열의 평균 (axis=0):", col_mean, col_mean.shape)

# axis=1: 각 행의 합 (결과 shape: (3,))
row_sum = A.sum(axis=1)
print("행의 합 (axis=1):", row_sum, row_sum.shape)

# keepdims=True: 차원을 유지하여 (1,4) shape으로 결과를 받음
col_mean_keepdims = A.mean(axis=0, keepdims=True)
print("shape:", col_mean_keepdims, col_mean_keepdims.shape)

# any/all: 논리 연산 집계
mask = (A % 2 == 0) # 짝수인 원소는 True
print("\n짝수인 원소는 True:\n", mask)
# 각 행에 짝수가 하나라도 있는지 (any)
print("짝수가 하나라도 있는지?", mask.any(axis=1))

# argmax: 각 열에서 가장 큰 값의 인덱스(행 번호)를 반환
print("가장 큰 값의 인덱스:", A.argmax(axis=0))

Original Array A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

열의 평균 (axis=0): [4. 5. 6. 7.] (4,)
행의 합 (axis=1): [ 6 22 38] (3,)
shape: [[4. 5. 6. 7.]] (1, 4)

짝수인 원소는 True:
 [[ True False  True False]
 [ True False  True False]
 [ True False  True False]]
짝수가 하나라도 있는지? [ True  True  True]
가장 큰 값의 인덱스: [2 2 2 2]


### 불리언 인덱싱 (Boolean Masking)

조건식을 이용해 `True`/`False`로 이루어진 불리언 배열(마스크)을 만들고, 이 마스크를 사용해 `True`에 해당하는 위치의 원소만 선택하는 기법입니다. 이 결과는 항상 **복사본(copy)**을 반환합니다.

- **`&`**: AND
- **`|`**: OR
- **`~`**: NOT

**`np.where(condition, x, y)`**: `condition`이 `True`인 위치에는 `x`의 값을, `False`인 위치에는 `y`의 값을 채운 새로운 배열을 반환합니다.

In [8]:
A = np.arange(-5, 6)
print("Original Array A:", A)

# 조건: 0보다 크면서(&) 짝수인 원소
mask = (A > 0) & (A % 2 == 0)
print("(A > 0) & (A % 2 == 0):", mask)

# 마스크를 이용해 원소 선택
print("조건에 만족하는 원소는?:", A[mask])

# np.where: A가 0보다 작으면 0으로, 아니면 원래 값(A)으로 대체
B = np.where(A < 0, 0, A)
print("np.where(A < 0, 0, A):", B)

# np.nonzero: 마스크가 True인 원소들의 인덱스를 반환
idx = np.nonzero(mask)
print("조건의 만족하는 원소의 인덱스?:", idx)

Original Array A: [-5 -4 -3 -2 -1  0  1  2  3  4  5]
(A > 0) & (A % 2 == 0): [False False False False False False False  True False  True False]
조건에 만족하는 원소는?: [2 4]
np.where(A < 0, 0, A): [0 0 0 0 0 0 1 2 3 4 5]
조건의 만족하는 원소의 인덱스?: (array([7, 9]),)


### 팬시 인덱싱 (Fancy Indexing)

정수 배열이나 리스트를 사용해 원하는 위치의 원소들을 **복사**하여 가져오는 방법입니다. 순서를 바꾸거나 중복 선택이 가능합니다.

- **`arr[ [row1, row2], [col1, col2] ]`**: `(row1, col1)`과 `(row2, col2)` 위치의 원소들을 선택합니다.
- **`np.ix_(rows, cols)`**: `rows`와 `cols`의 모든 조합에 해당하는 부분 행렬을 선택할 때 사용합니다.

In [9]:
A = np.arange(1, 13).reshape(3, 4)
print("Original Array A:\n", A)

# 행은 0, 2번 / 열은 1, 3번을 선택하여 부분 행렬 생성
rows = [0, 2]
cols = [1, 3]
sub_matrix = A[np.ix_(rows, cols)]
print("\n부분 행렬:\n", sub_matrix)

# 좌표별로 원소 선택: (2,3), (0,1), (2,0) 위치의 원소들을 순서대로 선택
selected_elements = A[[2, 0, 2], [3, 1, 0]]
print("\n선택한 원소:", selected_elements)

# take: 1차원으로 펼친 배열에서 특정 인덱스의 원소들을 가져옴
taken_elements = np.take(A, indices=[0, 3, 7], axis=None)
print("선택한 인덱스의 원소:", taken_elements)

Original Array A:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

부분 행렬:
 [[ 2  4]
 [10 12]]

선택한 원소: [12  2  9]
선택한 인덱스의 원소: [1 4 8]


## 5. 유니버설 함수(ufunc)와 벡터화

### ufunc & 벡터화 개념

**유니버설 함수(Universal Function, ufunc)**는 배열의 모든 원소에 대해 개별적으로 연산을 수행하는 함수입니다. 내부적으로 C 코드로 구현되어 있어 파이썬 반복문보다 훨씬 빠릅니다. 이 ufunc를 사용해 반복문을 제거하고 배열 전체에 연산을 적용하는 기법을 **벡터화(Vectorization)**라고 합니다.

`np.add`, `np.sin`, `np.exp` 등 대부분의 NumPy 수학 함수가 ufunc입니다.

In [10]:
# 0부터 2*pi까지 7개의 점을 생성
x = np.linspace(0, 2 * np.pi, 7)

# 벡터화 연산: sin(x)와 cos(x)를 계산하여 더함
y = np.sin(x) + np.cos(x)
print("y = sin(x) + cos(x):\n", y)

# out, where 인자 활용: 결과를 저장할 배열(out)을 미리 만들고, 조건(where)에 맞는 위치에만 계산 결과를 저장
z = np.empty_like(y) # y와 같은 shape과 dtype을 가진 빈 배열 생성
np.add(np.sin(x), np.cos(x), out=z, where=(x > 0))
print("\nResult with 'out' and 'where' (x > 0):\n", z)

y = sin(x) + cos(x):
 [ 1.         1.3660254  0.3660254 -1.        -1.3660254 -0.3660254
  1.       ]

Result with 'out' and 'where' (x > 0):
 [ 1.         1.3660254  0.3660254 -1.        -1.3660254 -0.3660254
  1.       ]


### ufunc 고급: `reduce`, `accumulate`, `outer`

- **`ufunc.reduce(arr, axis)`**: 지정된 축을 따라 ufunc을 누적 적용하여 차원을 축소합니다. `np.add.reduce(arr)`는 `np.sum(arr)`과 같습니다.
- **`ufunc.accumulate(arr, axis)`**: `reduce`와 비슷하지만 중간 계산 결과를 모두 포함하는 배열을 반환합니다. (누적 합, 누적 곱 등)
- **`ufunc.outer(a, b)`**: 두 1차원 벡터 `a`와 `b`의 모든 원소 조합에 대해 ufunc을 적용하여 2차원 배열을 생성합니다.

In [ ]:
a = np.array([1, 2, 3, 4])

# reduce: 모든 원소를 더함 (1+2+3+4)
s = np.add.reduce(a)
print("add.reduce(a):", s)

# accumulate: 누적 곱 계산 [1, 1*2, (1*2)*3, (1*2*3)*4]
pref = np.multiply.accumulate(a)
print("multiply.accumulate(a):", pref)

X = np.array([0, 1, 2])
Y = np.array([10, 20, 30])

# outer: X와 Y의 모든 원소 쌍에 대해 뺄셈 연산
# 결과 행렬의 (i, j) 원소는 X[i] - Y[j]가 됨
o = np.subtract.outer(X, Y)
print("\nsubtract.outer(X, Y):\n", o)

add.reduce(a): 10
multiply.accumulate(a): [ 1  2  6 24]

subtract.outer(X, Y):
 [[-10 -20 -30]
 [ -9 -19 -29]
 [ -8 -18 -28]]


## 6. 주요 함수 카탈로그

### 수학/통계 함수

- **수학 함수**: `np.exp`, `np.log`, `np.sqrt`, `np.sin`, `np.cos` 등
- **통계 함수**: `np.mean`, `np.std`, `np.var`, `np.sum`, `np.min`, `np.max`, `np.percentile` (분위수)
- **라운딩/클리핑**: `np.round`, `np.floor`, `np.ceil`, `np.clip` (최소/최대값 제한)

In [ ]:
X = np.array([0.1, 2.5, 9.9, -3.0])
print("Original Array X:", X)

# clip: X의 원소들을 -1과 5 사이의 값으로 제한
Y = np.clip(X, -1, 5)
print("Clipped array (-1, 5):", Y)

# log1p: log(1+x) 계산. x가 0에 가까울 때 정밀도를 높여줌
Z = np.round(np.log1p(np.abs(X)), 3)
print("log1p(abs(X)) rounded to 3 decimals:", Z)

# percentile: 1%, 50%(중앙값), 99% 위치의 값을 계산
q = np.percentile(X, [1, 50, 99])
print("1st, 50th, 99th percentiles:", q)

Original Array X: [ 0.1  2.5  9.9 -3. ]
Clipped array (-1, 5): [ 0.1  2.5  5.  -1. ]
log1p(abs(X)) rounded to 3 decimals: [0.095 1.253 2.389 1.386]
1st, 50th, 99th percentiles: [-2.907  1.3    9.678]


### 비교/논리 연산

원소별 비교 연산(`==`, `!=`, `<`, `>`)은 불리언 배열을 반환하며, `any()`/`all()` 함수와 결합하여 배열 전체 또는 특정 축의 조건을 확인할 수 있습니다.

- **`np.isfinite(arr)`**, **`np.isnan(arr)`**: 유한한 값인지, NaN(Not a Number)인지 확인
- **`np.signbit(arr)`**: 부호 비트를 확인하여 음수 여부를 빠르게 판단 (`True`이면 음수)

In [ ]:
A = np.array([[1, -2, 3], [0, 5, -6]])

# A > 0은 양수 여부, ~np.signbit(A)는 음수가 아닌지(0 또는 양수) 확인
# 즉, 양수인 원소만 True가 됨
mask = (A > 0) & (~np.signbit(A))
print("Mask for positive numbers:\n", mask)

# 각 행에 양수가 하나라도 있는지 확인
print("\nAny positive in each row?", mask.any(axis=1))

# 전체 원소 중 양수의 비율 계산 (True=1, False=0으로 계산됨)
print("Proportion of positive numbers:", mask.mean())

Mask for positive numbers:
 [[ True False  True]
 [False  True False]]

Any positive in each row? [ True  True]
Proportion of positive numbers: 0.5


### NaN / Inf 처리

`NaN`(Not a Number)이나 `Inf`(Infinity)는 연산 과정에서 전파되어 전체 결과를 오염시킬 수 있습니다. 이를 안전하게 처리하는 것이 중요합니다.

- **`np.nanmean`, `np.nansum` 등**: `NaN`을 무시하고 계산하는 함수들
- **`np.isfinite(arr)`**: `NaN`과 `Inf`가 아닌 유한한 값만 `True`로 표시하여 필터링에 사용
- **`np.nan_to_num(arr)`**: `NaN`, `Inf`, `-Inf`를 지정된 값(기본값 0)으로 대체

In [ ]:
X = np.array([1.0, np.nan, np.inf, -np.inf, 3.0])
print("Original array with NaN/Inf:", X)

# 유한한 값만 필터링하기 위한 마스크 생성
mask = np.isfinite(X)
print("\nFinite value mask:", mask)
print("Mean of finite values:", X[mask].mean())

# nan_to_num을 이용해 NaN과 Inf를 대체
X2 = np.nan_to_num(X, nan=0.0, posinf=1e3, neginf=-1e3)
print("\nArray after nan_to_num:", X2)

# nanmean: NaN을 무시하고 평균 계산
print("\nnanmean of [1.0, np.nan, 2.0]:", np.nanmean([1.0, np.nan, 2.0]))

Original array with NaN/Inf: [  1.  nan  inf -inf   3.]

Finite value mask: [ True False False False  True]
Mean of finite values: 2.0

Array after nan_to_num: [    1.     0.  1000. -1000.     3.]

nanmean of [1.0, np.nan, 2.0]: 1.5


## 7. 선형대수와 고급 연산

### 행렬 곱셈: `@`, `dot`, `matmul`, `tensordot`

- **`@` 연산자** (또는 `np.matmul`): 2차원 배열(행렬) 간의 곱셈에 가장 직관적이고 권장되는 방식. 3차원 이상의 배열에서는 마지막 두 축에 대해 행렬 곱을 수행하고, 나머지 앞쪽 축들은 브로드캐스팅됩니다.
- **`np.dot`**: 1차원 벡터 간에는 내적(dot product)을, 2차원 배열 간에는 행렬 곱을 수행합니다.
- **`np.tensordot(a, b, axes)`**: 고차원 텐서 간의 복잡한 곱셈(축약, contraction)을 `axes` 인자를 통해 명시적으로 정의할 수 있습니다.

In [ ]:
A = np.arange(6).reshape(2, 3)     # (2, 3)
B = np.arange(12).reshape(3, 4)    # (3, 4)

# @ 연산자를 이용한 행렬 곱셈 (2,3) @ (3,4) -> (2,4)
C = A @ B
print("Matrix multiplication A @ B:\n", C)
print("Shape of C:", C.shape)

x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
# dot을 이용한 벡터 내적 (1*4 + 2*5 + 3*6)
dot_product = np.dot(x, y)
print("\nDot product of x and y:", dot_product)

T1 = np.arange(24).reshape(2, 3, 4)
T2 = np.arange(12).reshape(3, 4)
# tensordot: T1의 1, 2번 축과 T2의 0, 1번 축을 곱하고 합산
TD = np.tensordot(T1, T2, axes=([1, 2], [0, 1]))
print("\nResult of tensordot:", TD)
print("Shape of TD:", TD.shape)

Matrix multiplication A @ B:
 [[20 23 26 29]
 [56 68 80 92]]
Shape of C: (2, 4)

Dot product of x and y: 32

Result of tensordot: [ 506 1298]
Shape of TD: (2,)


### 행렬 분해 및 방정식 풀이

`np.linalg` 모듈은 선형대수를 위한 다양한 함수를 제공합니다.

- **`svd`**: 특이값 분해(Singular Value Decomposition). 차원 축소, 데이터 압축 등에 활용됩니다.
- **`eig` / `eigh`**: 고유값(eigenvalue)과 고유벡터(eigenvector)를 계산합니다. `eigh`는 대칭 행렬(symmetric matrix)에 사용하며 수치적으로 더 안정적입니다.
- **`solve`**: $Ax=b$ 형태의 선형 연립방정식의 해 $x$를 구합니다.
- **`pinv` / `lstsq`**: 역행렬이 존재하지 않거나 행렬이 정방 행렬이 아닐 때, 최소 제곱 해(least-squares solution)를 구합니다.

In [ ]:
# 대칭 행렬 A 생성
A = np.array([[3., 2.], [2., 6.]])
b = np.array([2., -8.])
print("Matrix A:\n", A)
print("Vector b:", b)

# SVD (특이값 분해)
U, S, Vt = np.linalg.svd(A, full_matrices=False)
A_rec = U @ np.diag(S) @ Vt # 분해된 행렬들로 원본 복원
print("\nIs A reconstructed from SVD correctly?", np.allclose(A, A_rec))

# eigh (대칭 행렬의 고유값 분해)
w, v = np.linalg.eigh(A)
print("Eigenvalues:", w)
print("Eigenvectors:\n", v)

# solve (선형 방정식 Ax = b 풀이)
x_solve = np.linalg.solve(A, b)
print("\nSolution x from solve:", x_solve)
# 검증: A @ x_solve가 b와 거의 같은지 확인
print("Verification (A @ x_solve):", A @ x_solve)

# lstsq (최소 제곱 해)
x_ls, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)
print("Solution x from lstsq:", x_ls)

Matrix A:
 [[3. 2.]
 [2. 6.]]
Vector b: [ 2. -8.]

Is A reconstructed from SVD correctly? True
Eigenvalues: [2. 7.]
Eigenvectors:
 [[-0.89442719  0.4472136 ]
 [ 0.4472136   0.89442719]]

Solution x from solve: [ 2. -2.]
Verification (A @ x_solve): [ 2. -8.]
Solution x from lstsq: [ 2. -2.]


### `einsum`: 아인슈타인 표기법

`einsum`은 축의 관계를 문자로 표현하여 전치, 행렬 곱, 내적, 외적 등 다양한 텐서 연산을 하나의 함수로 간결하게 표현할 수 있게 해줍니다. 복잡한 연산에서 불필요한 중간 배열 생성을 막아 메모리 효율과 성능을 높일 수 있습니다.

- **`'ik,kj->ij'`**: 행렬 곱. `i`행 `k`열과 `k`행 `j`열을 곱하고 공통 축 `k`에 대해 합산하여 `i`행 `j`열을 만듭니다.
- **`'ij->ji'`**: 전치. `i`행 `j`열을 `j`행 `i`열로 바꿉니다.
- **`'i,i->'`**: 내적. 두 벡터의 같은 위치 `i`의 원소들을 곱하고 모두 합산하여 스칼라를 만듭니다.
- **`'i,j->ij'`**: 외적. 두 벡터의 원소 조합 `i`, `j`로 2차원 행렬을 만듭니다.

In [ ]:
A = np.arange(6).reshape(2, 3)
B = np.arange(12).reshape(3, 4)
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

# 행렬 곱
C1 = A @ B
C2 = np.einsum('ik,kj->ij', A, B)
print("Are matrix products C1 and C2 close?", np.allclose(C1, C2))

# 외적
outer_prod = np.einsum('i,j->ij', x, y)
print("\nOuter product shape:", outer_prod.shape)
print(outer_prod)

# 전치
transpose_A = np.einsum('ij->ji', A)
print("\nTranspose of A:\n", transpose_A)
print("Transpose shape:", transpose_A.shape)

Are matrix products C1 and C2 close? True

Outer product shape: (3, 3)
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]

Transpose of A:
 [[0 3]
 [1 4]
 [2 5]]
Transpose shape: (3, 2)


## 8. 실전 패턴 및 성능 최적화

### 배치 연산 패턴

머신러닝에서는 여러 개의 데이터 샘플(배치)을 한 번에 처리하는 경우가 많습니다. 보통 첫 번째 축을 배치 축(N)으로 사용하며, `(N, ...)` 형태의 배열에 대해 벡터화 연산을 적용하여 효율을 높입니다.

In [ ]:
# 5개의 데이터 샘플, 각 샘플은 4개의 특성(feature)을 가짐 (N=5, d=4)
X = np.random.randn(5, 4)
# 가중치 행렬 (d=4, k=3)
W = np.random.randn(4, 3)

# 배치 선형 변환: (5,4)와 (4,3)을 곱해 (5,3) 결과를 얻음
# einsum으로 명확하게 표현: 'nd,dk->nk'
Y = np.einsum('nd,dk->nk', X, W) # 또는 Y = X @ W
print("Batch linear transformation shape (Y):", Y.shape)

# 배치 코사인 유사도 (X의 모든 샘플 쌍 간의 유사도 계산)
# 1. 각 행(샘플)을 L2 norm으로 정규화
X_norm = np.linalg.norm(X, axis=1, keepdims=True) + 1e-9 # 0으로 나누는 것을 방지
Xn = X / X_norm
# 2. 정규화된 행렬과 그 전치 행렬을 곱함
S = Xn @ Xn.T
print("\nBatch cosine similarity matrix shape (S):", S.shape) # (5, 5)

Batch linear transformation shape (Y): (5, 3)

Batch cosine similarity matrix shape (S): (5, 5)


### 메모리 모델: View vs Copy

NumPy 연산이 원본 데이터를 공유하는 **뷰(View)**를 반환하는지, 아니면 새로운 메모리 공간을 할당하는 **복사본(Copy)**을 반환하는지 이해하는 것은 매우 중요합니다. 의도치 않은 데이터 변경을 막을 수 있기 때문입니다.

- **주로 뷰를 반환**: 슬라이싱, `reshape`, `T`(전치), `ravel`
- **주로 복사본을 반환**: `astype`, `flatten`, 산술 연산, 불리언/팬시 인덱싱

**`np.shares_memory(arr1, arr2)`**: 두 배열이 메모리를 공유하는지 확인할 수 있습니다.

In [ ]:
X = np.arange(12).reshape(3, 4)

# 슬라이싱은 뷰를 반환할 가능성이 높음
S = X[:, ::2] # 모든 행, 2칸씩 건너뛰는 열
print("Does S share memory with X?", np.shares_memory(X, S))

# 뷰를 수정하면 원본도 바뀜
S[0, 0] = 999
print("X[0, 0] after modifying S:", X[0, 0])

# astype은 항상 복사본을 반환
Y = X.astype(np.float32)
print("\nDoes Y (from astype) share memory with X?", np.shares_memory(X, Y))

Does S share memory with X? True
X[0, 0] after modifying S: 999

Does Y (from astype) share memory with X? False


### 마스크된 배열 (Masked Array)

`np.ma` 모듈은 결측치나 유효하지 않은 값을 계산에서 제외하고 싶을 때 사용합니다. 불리언 마스크를 이용해 특정 값을 가리고, 집계 함수 등은 가려진 값을 자동으로 무시합니다.

In [ ]:
import numpy.ma as ma

x = np.array([1.0, -2.0, 5.0, -4.0])

# x < 0 인 값을 마스킹 (가림)
m = ma.masked_where(x < 0, x)
print("Masked array (negative values hidden):", m)

# 평균 계산 시 마스크된 값(-2.0, -4.0)은 무시됨 (1.0 + 5.0) / 2
print("Mean of masked array:", m.mean())

# 마스크 확인 (True가 가려진 값)
print("The mask itself:", m.mask)

# 가려진 값을 0으로 채워서 일반 배열로 변환
print("Filled with 0:", m.filled(0))

Masked array (negative values hidden): [1.0 -- 5.0 --]
Mean of masked array: 3.0
The mask itself: [False  True False  True]
Filled with 0: [1. 0. 5. 0.]


### 구조화 배열 (Structured Array)

하나의 배열에 여러 다른 데이터 타입의 필드(열)를 가질 수 있게 해줍니다. 마치 데이터베이스의 테이블이나 Pandas의 DataFrame처럼 사용할 수 있는 경량 테이블입니다.

In [ ]:
# 'name'(문자열), 'age'(정수), 'score'(실수) 필드를 갖는 dtype 정의
dt = [('name', 'U10'), ('age', 'i4'), ('score', 'f4')]

data = [('Ann', 23, 88.5), ('Bob', 31, 91.2), ('Cat', 27, 83.0)]
a = np.array(data, dtype=dt)
print("Structured array:\n", a)

# 필드 이름으로 데이터 접근
print("\nNames:", a['name'])

# 'score' 필드를 기준으로 정렬하고, 정렬된 순서의 'name' 필드를 출력
print("Names sorted by score:", np.sort(a, order='score')['name'])

# 'age'가 25보다 큰 레코드 필터링
mask = a['age'] > 25
print("\nRecords where age > 25:\n", a[mask])

Structured array:
 [('Ann', 23, 88.5) ('Bob', 31, 91.2) ('Cat', 27, 83. )]

Names: ['Ann' 'Bob' 'Cat']
Names sorted by score: ['Cat' 'Ann' 'Bob']

Records where age > 25:
 [('Bob', 31, 91.2) ('Cat', 27, 83. )]


### 날짜/시간 배열 (`datetime64`)

시계열 데이터를 다루기 위한 `datetime64`와 시간 간격을 나타내는 `timedelta64` 타입을 지원합니다. 벡터화된 날짜/시간 연산이 가능합니다.

In [ ]:
# 'D'(Day) 단위의 datetime64 배열 생성
d = np.array(['2025-01-01', '2025-01-10'], dtype='datetime64[D]')

# 두 날짜 간의 차이 (timedelta64)
delta = d[1] - d[0]
print("Time difference:", delta)

# 시간 단위로 변환
hours = delta.astype('timedelta64[h]')
print("Difference in hours:", hours)

# 특정 기간의 날짜 배열 생성 및 주말 필터링
week = np.arange('2025-01-01', '2025-01-08', dtype='datetime64[D]')
# 월요일=0, ... 일요일=6. 토요일(5) 또는 일요일(6) 찾기
weekend_mask = (week.astype('datetime64[D]').astype(int) + 4) % 7 >= 5
print("\nWeekdays:", week[~weekend_mask])

Time difference: 9 days
Difference in hours: 216 hours

Weekdays: ['2025-01-01' '2025-01-02' '2025-01-05' '2025-01-06' '2025-01-07']


### 파일 I/O

NumPy 배열을 파일로 저장하고 불러올 수 있습니다.

- **`np.save('file.npy', arr)` / `np.load('file.npy')`**: 단일 배열을 바이너리 `.npy` 형식으로 저장/로드. 빠르고 정확합니다.
- **`np.savez('archive.npz', name1=arr1, name2=arr2)`**: 여러 배열을 압축된 `.npz` 아카이브로 저장.
- **`np.memmap`**: 디스크에 있는 파일을 메모리에 있는 배열처럼 다룰 수 있게 해줍니다. 메모리보다 훨씬 큰 배열을 다룰 때 유용합니다.

In [ ]:
X = np.arange(12).reshape(3, 4)
y = np.arange(3)

# 단일 배열 저장
np.save('X_array.npy', X)

# 여러 배열 저장
np.savez('packed_arrays.npz', X_data=X, y_data=y)

# 단일 배열 로드
X2 = np.load('X_array.npy')
print("Loaded X2 shape:", X2.shape)

# 여러 배열 로드
archive = np.load('packed_arrays.npz')
print("Keys in archive:", list(archive.keys()))
print("Content of y_data:", archive['y_data'])
archive.close() # 파일을 닫아주는 것이 좋습니다.

Loaded X2 shape: (3, 4)
Keys in archive: ['X_data', 'y_data']
Content of y_data: [0 1 2]


### 성능 측정

최적화의 첫걸음은 성능 측정입니다. `time` 모듈의 `perf_counter`나 Jupyter의 `%timeit` 매직 명령어를 사용해 코드 실행 시간을 측정하고, 벡터화의 효과를 직접 확인할 수 있습니다.

In [ ]:
import time

n = 1_000_000
x = np.random.rand(n)

# 파이썬 루프를 이용한 합산
s = 0.0
start = time.perf_counter()
for v in x: s += v
loop_t = time.perf_counter() - start

# NumPy 벡터화를 이용한 합산
start = time.perf_counter()
s2 = x.sum()
np_t = time.perf_counter() - start

print(f"Python loop: {loop_t:.6f} seconds")
print(f"NumPy sum():   {np_t:.6f} seconds")
print(f"NumPy is about {loop_t / max(np_t, 1e-9):.2f} times faster.")

Python loop: 0.357757 seconds
NumPy sum():   0.000841 seconds
NumPy is about 425.43 times faster.


### 고급 Strides 활용: 슬라이딩 윈도우

**주의: 고급 기법이며 잘못 사용하면 메모리 오류를 일으킬 수 있습니다.**

`as_strided` 함수를 사용하면 메모리 복사 없이, strides를 직접 조작하여 배열의 뷰를 만들 수 있습니다. 이를 이용해 이동 평균(moving average) 계산 등을 매우 효율적으로 구현할 수 있습니다.

In [ ]:
from numpy.lib.stride_tricks import as_strided

x = np.arange(10, dtype=float)
win = 3 # 윈도우 크기

# 슬라이딩 윈도우 뷰의 shape과 strides 계산
shape = (x.size - win + 1, win)
strides = (x.strides[0], x.strides[0])

# as_strided로 뷰 생성
Xw = as_strided(x, shape=shape, strides=strides)
print("Sliding window view (Xw):\n", Xw)

# 뷰를 이용해 이동 평균 계산
mov_avg = Xw.mean(axis=1)
print("\nMoving average:", mov_avg)

Sliding window view (Xw):
 [[0. 1. 2.]
 [1. 2. 3.]
 [2. 3. 4.]
 [3. 4. 5.]
 [4. 5. 6.]
 [5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]

Moving average: [1. 2. 3. 4. 5. 6. 7. 8.]


### Gather / Scatter 연산

- **Gather (모으기)**: 인덱스를 사용해 흩어져 있는 데이터를 모으는 연산. (`take`, `take_along_axis`)
- **Scatter (뿌리기)**: 특정 인덱스 위치에 데이터를 쓰는 연산. (`put`, `put_along_axis`)

**`np.add.at(arr, indices, values)`**: `indices`에 중복이 있을 때, 해당 위치에 `values`를 원자적으로(atomically) 더해줍니다. 히스토그램이나 그룹별 집계에 유용합니다.

In [ ]:
# 카테고리별 카운팅 (add.at 활용)
x = np.array([0, 1, 2, 0, 1, 2, 2]) # 0, 1, 2 세 개의 카테고리
acc = np.zeros(3, dtype=int) # 각 카테고리 개수를 저장할 배열

# x의 각 원소를 인덱스로 사용하여 acc 배열에 1씩 더함
np.add.at(acc, x, 1)
print("Category counts:", acc) # [2, 2, 3] -> 0번 2개, 1번 2개, 2번 3개

# put_along_axis 예제
A = np.arange(12).reshape(3, 4)
print("\nOriginal A:\n", A)
cols = np.array([[1], [3], [0]]) # 각 행에서 값을 변경할 열 인덱스

# axis=1(열 방향)을 따라, cols에 지정된 위치의 값들을 999로 변경
np.put_along_axis(A, cols, 999, axis=1)
print("A after put_along_axis:\n", A)

Category counts: [2 2 3]

Original A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
A after put_along_axis:
 [[  0 999   2   3]
 [  4   5   6 999]
 [999   9  10  11]]


### 정렬 및 순위

- **`np.sort(arr)`**: 배열을 정렬한 복사본을 반환.
- **`arr.sort()`**: 배열을 제자리(in-place) 정렬.
- **`np.argsort(arr)`**: 배열을 정렬하는 데 필요한 인덱스를 반환. 원본 데이터의 순서를 유지하면서 정렬된 순서로 접근할 때 매우 유용합니다.
- **`np.partition(arr, k)`**: `k`번째 원소를 기준으로 `k`보다 작은 값들은 왼쪽, 큰 값들은 오른쪽에 오도록 부분 정렬합니다. 전체를 정렬할 필요 없이 Top-K 값을 찾을 때 효율적입니다.
- **`np.lexsort((key2, key1))`**: 다중 키 정렬. 마지막에 주어진 키(`key1`)부터 순서대로 정렬합니다.

In [ ]:
x = np.array([7, 1, 5, 9, 3])

# argsort: 정렬 순서에 해당하는 원본 인덱스를 반환
idx = x.argsort()
print("Original array x:", x)
print("Sorted indices (argsort):", idx)
print("Sorted array x[idx]:", x[idx])

# argpartition: 상위 3개 값 찾기
k = 3
top_k_indices = np.argpartition(x, -k)[-k:] # -k는 뒤에서 k번째
print("\nTop 3 values:", np.sort(x[top_k_indices]))

# lexsort: 다중 키 정렬 (score 오름차순, 동점 시 age 내림차순)
score = np.array([90, 80, 90, 95, 80])
age = np.array([20, 30, 25, 22, 30])
# 정렬 우선순위: score(오름차순), -age(내림차순)
order = np.lexsort((-age, score))
print("\nSorted by score(asc), then age(desc):\n", list(zip(score[order], age[order])))

Original array x: [7 1 5 9 3]
Sorted indices (argsort): [1 4 2 0 3]
Sorted array x[idx]: [1 3 5 7 9]

Top 3 values: [5 7 9]

Sorted by score(asc), then age(desc):
 [(np.int64(80), np.int64(30)), (np.int64(80), np.int64(30)), (np.int64(90), np.int64(25)), (np.int64(90), np.int64(20)), (np.int64(95), np.int64(22))]


### 그룹별 집계

카테고리(그룹)별로 합계, 평균 등의 통계를 계산하는 패턴입니다.

- **`np.unique(arr, return_inverse=True)`**: 고유한 값들과 함께, 원본 배열의 각 원소가 어떤 고유값에 해당하는지 알려주는 인덱스(`inverse_indices`)를 반환합니다.
- **`np.bincount(x, weights=y)`**: `x` 배열(정수 인덱스)을 기준으로 `y` 배열(가중치)의 값을 누적합니다. 그룹별 합계/카운트를 매우 빠르게 계산할 수 있습니다.

In [ ]:
cats = np.array(['A', 'B', 'A', 'C', 'B', 'A'])
vals = np.array([10., 20., 15., 7., 13., 12.])

# unique를 이용해 카테고리를 정수 인덱스로 변환
keys, inv_indices = np.unique(cats, return_inverse=True)
print("Unique keys:", keys)
print("Inverse indices:", inv_indices) # [0 1 0 2 1 0]

# bincount로 그룹별 합계 및 개수 계산
sum_by_group = np.bincount(inv_indices, weights=vals)
count_by_group = np.bincount(inv_indices)
print("\nSum by group:", sum_by_group)
print("Count by group:", count_by_group)

# 그룹별 평균 계산
mean_by_group = sum_by_group / count_by_group
print("Mean by group:", mean_by_group)

# 그룹 평균을 이용해 데이터 중심화 (각 값에서 해당 그룹의 평균을 뺌)
centered_vals = vals - mean_by_group[inv_indices]
print("\nCentered values:\n", centered_vals.round(2))

Unique keys: ['A' 'B' 'C']
Inverse indices: [0 1 0 2 1 0]

Sum by group: [37. 33.  7.]
Count by group: [3 2 1]
Mean by group: [12.33333333 16.5         7.        ]

Centered values:
 [-2.33  3.5   2.67  0.   -3.5  -0.33]


### 재현성 및 샘플링 전략

실험의 재현성을 위해 `np.random.default_rng(seed)`를 사용합니다. 생성된 `Generator` 객체는 데이터를 섞거나 샘플링하는 다양한 메서드를 제공합니다.

- **`rng.permutation(x)`**: `x`가 정수이면 0부터 `x-1`까지의 순열을, 배열이면 배열을 섞은 복사본을 반환합니다.
- **`rng.shuffle(arr)`**: 배열을 제자리에서 섞습니다.
- **`rng.choice(a, size, replace=True, p=None)`**: 배열 `a`에서 주어진 `size`만큼 샘플링합니다. `replace=False`는 비복원 추출, `p`는 각 원소가 뽑힐 확률을 지정합니다.

In [ ]:
rng = np.random.default_rng(2025)

# 인덱스를 섞어 학습/테스트 데이터 분리
indices = rng.permutation(10)
train_idx, test_idx = indices[:7], indices[7:]
print("Train indices:", train_idx)
print("Test indices:", test_idx)

# 클래스 불균형 샘플링 (1이 뽑힐 확률을 0.7로 설정)
probabilities = np.array([0.3, 0.7]) # 클래스 0, 1에 대한 확률
samples = rng.choice([0, 1], size=12, p=probabilities)
print("\nWeighted samples:", samples)

Train indices: [2 3 0 9 1 4 5]
Test indices: [8 7 6]

Weighted samples: [1 1 1 0 1 0 0 0 1 1 0 1]


### 수치 안정성 (Numerical Stability)

컴퓨터에서 실수를 다룰 때는 오버플로(overflow), 언더플로(underflow) 등의 문제가 발생할 수 있습니다. 특히 `exp` 함수처럼 값이 매우 커질 수 있는 연산에서는 수치 안정성을 고려해야 합니다.

**Log-Sum-Exp 트릭**: `log(sum(exp(x)))`를 계산할 때, `x`의 최댓값을 먼저 빼주어 오버플로를 방지하는 기법입니다. Softmax 함수를 안정적으로 계산할 때 핵심적으로 사용됩니다.

In [ ]:
x = np.array([1000., 1001., 999.])
# np.exp(x) # 이 코드는 오버플로 경고를 발생시킬 수 있습니다.

# 안정적인 Softmax 계산
def stable_softmax(x):
    # 1. 최댓값을 빼서 중심화 (오버플로 방지)
    m = x.max(keepdims=True)
    e_x = np.exp(x - m)
    # 2. 합계로 나누어 확률값으로 변환
    return e_x / (e_x.sum(keepdims=True) + 1e-9)

softmax_result = stable_softmax(x)
print("Stable softmax result:\n", softmax_result.round(6))
print("Sum of softmax result:", softmax_result.sum())

# 안정적인 Log-Sum-Exp 계산
def log_sum_exp(x):
    m = x.max()
    return m + np.log(np.sum(np.exp(x - m)))

lse_result = log_sum_exp(x)
print("\nLog-sum-exp result:", lse_result)

Stable softmax result:
 [0.244728 0.665241 0.090031]
Sum of softmax result: 0.9999999993347589

Log-sum-exp result: 1001.4076059644444


## 마무리 - 베스트 프랙티스

NumPy를 효과적으로 사용하기 위한 체크리스트입니다.

1.  **입력 확인**: 배열의 `shape`, `dtype`을 항상 인지하고, `np.isfinite` 등으로 결측치나 이상치를 확인합니다.
2.  **연산 확인**: `axis`와 `keepdims` 인자를 정확히 사용하여 의도한 대로 집계하고, 브로드캐스팅이 어떻게 동작할지 예측합니다.
3.  **성능 확인**: 가능한 모든 곳에서 반복문 대신 벡터화된 연산을 사용하고, 큰 배열을 다룰 때는 `out` 인자를 활용해 불필요한 임시 배열 생성을 줄입니다.
4.  **코드의 명확성**: 복잡한 연산은 `einsum`을 사용하거나, 중간 변수에 의미 있는 이름을 붙여 가독성을 높입니다.

In [ ]:
# 실용적인 유틸리티 함수 예시

def softmax(x, axis=-1):
    """입력 배열 x에 대해 지정된 축을 따라 안정적인 softmax를 계산합니다."""
    # 입력을 NumPy 배열로 변환 (리스트 등이 들어와도 처리 가능하게 함)
    x = np.asarray(x)
    # 수치 안정성을 위해 입력 값에서 최댓값을 뺍니다 (오버플로우 방지).
    # keepdims=True로 차원을 유지하여 브로드캐스팅이 가능하게 합니다.
    m = x.max(axis=axis, keepdims=True)
    # 각 원소에서 최댓값을 뺀 후 exp 함수를 적용합니다.
    e = np.exp(x - m)
    # exp 결과의 합으로 나누어 각 원소를 확률값으로 변환합니다.
    # 분모에 작은 값(1e-9)을 더해 0으로 나누는 오류를 방지합니다.
    return e / (e.sum(axis=axis, keepdims=True) + 1e-9)

def standardize(X, axis=0):
    """입력 배열 X를 지정된 축을 따라 표준화합니다 (평균 0, 표준편차 1)."""
    # 지정된 축(기본값 axis=0, 즉 열 방향)을 따라 평균을 계산합니다.
    # keepdims=True로 차원을 유지하여 브로드캐스팅이 가능하게 합니다.
    mu = X.mean(axis=axis, keepdims=True)
    # 지정된 축을 따라 표준편차를 계산합니다.
    # 분모에 작은 값(1e-8)을 더해 0으로 나누는 오류를 방지합니다.
    sd = X.std(axis=axis, keepdims=True) + 1e-8
    # (원본 값 - 평균) / 표준편차 공식을 사용하여 표준화합니다.
    # 브로드캐스팅을 통해 각 원소에서 해당 축의 평균을 빼고 표준편차로 나눕니다.
    return (X - mu) / sd

x_test = np.arange(12).reshape(3, 4).astype(float)

softmax_output = softmax(x_test, axis=1)
standardized_output = standardize(x_test, axis=0)

print("Test array:\n", x_test)
print("\nSoftmax output (axis=1):\n", softmax_output.round(4))
print("\nStandardized output (axis=0):\n", standardized_output.round(4))

Test array:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

Softmax output (axis=1):
 [[0.0321 0.0871 0.2369 0.6439]
 [0.0321 0.0871 0.2369 0.6439]
 [0.0321 0.0871 0.2369 0.6439]]

Standardized output (axis=0):
 [[-1.2247 -1.2247 -1.2247 -1.2247]
 [ 0.      0.      0.      0.    ]
 [ 1.2247  1.2247  1.2247  1.2247]]
